# Generated by Django 4.1.7 on 2023-03-12 08:42

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[core.validators.first_letter_capitalized])),
                ('last_name', models.CharField(max_length=20, validators=[core.validators.first_letter_capitalized])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
